### ISSUE TITLE
Issue with compiling

### ISSUE THREAD

**Issue by BLB5000** [dbdexter-dev/meteor_demod#3]
Hi,  I love this program too & thank you very much for releaseing it. 
 Lately I have had an issue compiling it though & can't make it. I originally made it on my R-pi 3  & had it working though I deleted it or re-installed os on the pi(stupidly) and I lost it.. I can't compile it on anything. It says tui.c error: 'VERSION' undeclared (first use in this function); did you mean '_SC_VERSION'. Please help me I don't understand what is happening. I did manage to compile it successfully on the R-pi again however lately, but when I go to run it in the terminal it responds with: segmentation fault. I can't fix that either. Is there a way possibly I could get a precompiled copy of this programs exe from anywhere? If so where please? Also any advice anyone could give me would be greatly appreciated. Thank you.

**Comment by dbdexter-dev** [comment]
Hi,
Try going to the project root and running `make clean && make`, VERSION is defined in the main Makefile and not in the one inside src. If that doesn't work, you can try with this precompiled binary: https://gofile.io/?c=j4dkxd
If that doesn't work either, it's probably an issue with the libraries you have installed. I can statically link the executable in that case, just let me know.

**Comment by BLB5000** [comment]
Hi,
 thank you for response. I'm sorry for my late response I was thinking the best way to describe this to you.. So I've given it a go at trying to install (from root) w/ [code]make clean && make install[/code] as well as trying to fix the VERSION syntax in the main Makefile (not the one in the src folder (:). I am still working on it atm. I did try to to download one of the binaries so see if I can get one to work however the Gofile page link you gave me hasn't got any files on it or the page is down (it's displaying the Gofile page but no files are displayed it just keeps showing me the loading symbol in the center of the page) & it won't display anything on the page just. If you wouldn't mind would you possibly be able to create the statically linked executable file like you were talking about for me please?.. I think it would save me soo much trouble right now. I'll still keep trying my best at installing in the meantime. Tyhank you again for offering too & being so kind.
 Take care huh Dbdexter, have a good day & weekend.. talk soon.
Kindest regards,
  ~BLB5000..

**Comment by dbdexter-dev** [comment]
Hi,
Here's the static binary: https://mega.nz/#!YBcAyYZL!9JKtUsYBNE204KIKuGiorfbL9i3xPtW7eWjii55YQuQ
I have a weird setup on my Pi, but it should work nonetheless.

**Comment by BLB5000** [comment]
Hi,
  thanks heaps.  I'll give it a try right now straight away. I'll let you
know how it goes but thanks again hey. Yeah I had a hunch you might of set
it up on a Pi some times it's programs act differently with other systems.
That's what I've noticed with mine at least anyway. They shouldn't be that
different though being that they both run using the same
architecture.  Anyhow, thanks again heaps (your a life-saver!). I hope rest
of your weekend & night.
 I'll talk with you again soon.
Kindest regards,   Blake.

**Comment by BLB5000** [comment]
Hi,
 good news I got it to work last night so thanks so much for that mate.
Only problem I have now is it's not decoding the signal fully properly the
signal status says locked all the time but the constellation image displays
in a thick or double line from left to right & bottom to top (diagonally)
do you have any idea why I may be getting that result.  Thanks again though
you're a life-saver & a legend & I love you program very much. It's really
good so thank you so much for releasing it!
Take care & talk soon.
 Kindest regards,
  Blake.

**Comment by dbdexter-dev** [comment]
Glad to hear it's at least running now haha
Yeah, I think I know why you're only seeing a line. That probably means the input samples are 8 bit and not 16 bit. I didn't really add support for 8 bit samples because I've only ever seen 16 bit I/Q recordings. If you still have the recording, you can try using this version I'm currently working on: https://mega.nz/#!FFdATYqA!KUksIahZJdDOvBVzVuc4Y8p3-4GIPiMSpeeBMO68svk

**Comment by BLB5000** [comment]
Hi Davide,
most of my recording are converted on Audacity to 16bits (as that & 32bit
or RAW are the only options). I recorded some of the most recent on
SDRSharp at 8bit like you were saying though but before that I had it set
at 16bit. Do you think I should go back to setting it for 16bit PCM
recordings? Thank you for your advice by the way, it's working much better
now. The constellation is spread out more all over the diagram, though it's
not staying in the 4-dot pattern that I thought it supposed to & also the
signal status only says 'Locked' every now and again & goes back to saying
'Acquiring'. Do you think I should set the PPL any lower than the default?
However it could be just the recording & me doing something wrong with it
like you said, I'll try to make another more decent recording tonight &
test it out. I'll update you on how I go with it. But thank you very much,
it's much better & getting close now. I'm heaps happy.. Yay! (=  Thank you
Davide. I hope you have a great day or night mate (whichever it is there)..
 Cheers.
Kindest regards,  Blake

**Comment by BLB5000** [comment]
I have been using a Airspy Mini too btw which records at samplerate of
3MSPS or 6MSPS (I am using 3 MSPS with SDRSharp on my Windows 10 PC). Would
that make a difference to the recording? Here are the technical specs from
the Airspy site:

   - Continuous 24 – 1700 MHz native RX range, down to DC with the
   SpyVerter option
   - 3.5 dB NF between 42 and 1002 MHz
   - Maximum RF input of +10 dBm
   - Tracking RF filters
   - 35dBm IIP3 RF front end
   - 12bit ADC @ 20 MSPS (10.4 ENOB, 70dB SNR, 95dB SFDR)
   - 10, 6 and 3 MSPS IQ output – Optimized for portable and tablets
   - Up to 6 MHz panoramic spectrum view
   - 0.5 ppm high precision, low phase noise clock
   - 4.5v software switchable Bias-Tee 100% Compatible with SpyVerter and
   High Performance LNA
   - IQ or Real, 16bit fixed or 32bit float output streams
   - No IQ imbalance, DC offset or 1/F noise at the center of the spectrum
   that plagues all the other SDRs
   - Best software support of all existing SDRs
   - No drivers required! 100% Plug-and-play on Windows Vista, Seven, 8,
   8.1 and 10, all Linux Flavors, Mac and Android
   - Compatible with Raspberry Pi, Odroid, Pine64 and UP boards
   - Operating temperature: -10°C to 40°C

I noticed it says 'No IQ imbalance' but I'm not sure if that would
complicate the audio recording or not. What do you think? Also I have a
Mini USB DVB-T RTL-SDR Realtek RTL2838U  (just like RTL2832U) & R820T Tuner
Receiver, I can use it instead but it just seems to me fairly basic & cheap
though it does work. I don't seem to pick the signals as clear or good.
Should I maybe use that instead?
Thanks heaps for your time & advice..
Best Regards,
  Blake

**Comment by BLB5000** [comment]
*Sorry I meant PLL (not PPL)  (=

**Comment by dbdexter-dev** [comment]
The default parameters for the PLL are good, there shouldn't be any need to change them really. And the "No IQ imbalance" spec is actually good for decoding the signal, so don't worry about that.
I'd suggest trying to record the baseband at 16 bits per sample, since the Airspy has a 12 bit ADC. Also make sure the signal is centered and strong enough (at least 5-10 dB SNR). Other than that, I'm not sure what else could be the issue. Maybe audacity is struggling with the resampling step? I only have access to a Realtek-based dongle, so I can't be sure the Airspy is compatible. I don't see a reason why it shouldn't be, but I'm not 100% positive.

**Comment by BLB5000** [comment]
Hey,
 thanks Davide yeah I'm heaps happy to say I got the program working last
night & decoded 3 images from last nights pass already! (= I  have been
working with it on & off most of the day. Now I am decoding some of my
older recordings that were abit longer trying to get a decent sized picture
from them as the first three were fairly small & I had to paste them
together. It will be good to get a clear & solid complete picture. But so
far it's all going heaps great & I'm more than happy with the results.
Thank you so much for sending me the programs they were a massive help &
for your excellent advice. I can't thank you enough for helping me.. Have a
great day too! Take care & talk soon.
Kindest regards,
  Blake.

**Comment by dbdexter-dev** [comment]
My pleasure Blake, good luck with your satellite hunting then!

**Comment by BLB5000** [comment]
Hi Davide,
how are you? Yeh the only problem I have is the program doesn't seem to
recognize or decode files over 2Gb. Is there someway to alter this. I guess
not, it's alright if there's not. I'm still just heaps glad to finally be
able to decode. Thank you for your time and support Davide. I hope you have
a nice day..
 Kindest regards,
   from Blake.

**Comment by dbdexter-dev** [comment]
Hi, yeah, not much I can do about that unfortunately. You can downsample your .wav files to ~150ksps though, since the LRPT signal only has a bandwidth of around 120kHz.
