### ISSUE TITLE
Cannot demodulate file from Gqrx after SoX conversion to .wav

### ISSUE THREAD

**Issue by lusiaold** [dbdexter-dev/meteor_demod#4]
Hello,
First of all, this is an awesome project, thanks to it it's possible to demodulate Meteor M2 signal on Linux! It's working well if I'm processing .wav files from SDRSharp or .wav files converted from `rtl_sdr`'s IQ files with iqToSharp tool. However, I can't get it to work with files recorded with Gqrx and converted from .raw to .wav with SoX. Here's an example:

```
➜ meteor_demod -o meteor_05_09_2019 /home/pawel/gqrx_20190509_190356_137900000_960000_fc_sox.wav -b 150                     
Warning: input file is not a valid .wav, assuming raw 16 bit data
[FATAL]: Please specify an input samplerate (-s <samplerate>)
```

When I specify input sample rate, the program runs, but demodulation isn't working properly. My file is around 11 minutes long and meteor_demod showed that it's nearly 30 minutes long after processing. The soft 8-bit file was very large after the processing (nearly 200 MB) and I couldn't decode any data with it (I tried with `weatherdump`, `medet` and LRPT Offline Decoder). Here's a command I'm using to convert .raw files to .wav: `sox --show-progress -t raw -r 960000 -b 32 -e float -c 2 input.raw output.wav`. The weird thing is that I can open the converted file without any problems in SDRSharp, furthermore, I can successfully demodulate it:

![image](https://user-images.githubusercontent.com/18142313/57523420-3b74b800-7325-11e9-84f0-c0355ff03b3c.png)

Output:

![image](https://user-images.githubusercontent.com/18142313/57524306-b76fff80-7327-11e9-8cd0-d32678d79485.png)

Here's how constellation diagram is looking like in `meteor_demod` (it's the same file as in the screenshot above), I used `-s 960000` parameter in the command:

![image](https://user-images.githubusercontent.com/18142313/57523905-8f33d100-7326-11e9-8721-9e78741d8960.png)

It often changes shapes

![image](https://user-images.githubusercontent.com/18142313/57524073-08332880-7327-11e9-9066-0ae7431f9e4e.png)

I can never see 4 dots on the diagram

Am I doing something wrong with `meteor_demod`? Shall I provide the .raw and .wav files?

**Comment by lusiaold** [comment]
It turned out that it wasn't an issue with demodulator, but with the file itself. I made a simple flowgraph in GNU Radio Companion to convert .raw files to .wav files:
![image](https://user-images.githubusercontent.com/18142313/57589334-c969c200-7522-11e9-8e2e-7f18681b3929.png)

I still don't know why SDR# would read it, but `meteor_demod` wouldn't, but at least I found a way to demodulate and process everything on Linux :smiley:

**Comment by dbdexter-dev** [comment]
Hi, thanks for checking out my project!

I think I know why you weren't able to decode the converted .wav file: the output format was 32-bit signed samples, and I only support 8-bit unsigned or 16-bit signed samples since most SDR recordings use one of those two encodings. You can still use sox, just change the output format to either of those and you should be good to go.

**Comment by cytrinox** [comment]
@PawelPleskaczynski I've the same problem with raw IQ recordings from gqrx. I convert the raw file with sox to a wav and demod with SDR# works fine. When i convert the floatingpoint wav to signed-int 16bits, meteor_demod can't demodulate the file (even unsigned 8bits won't work).

I've rebuild your gnuradio flowchart without luck. meteor_demod is not able to demod the output wav. Could you please share your grc file, maybe I've missed something?

**Comment by lusiaold** [comment]
@cytrinox sure, I'll send it later today

**Comment by cytrinox** [comment]
I found out that in gqrx, I have an positive channel filter offset (70kHz), so from my understanding the iq recording is not centered at the target frequence. I assume it is important that when recording with gqrx, the hardware frequency must exactly match the Meteor frequency (the channel filter offset must be zero). In 2 hours there is the next meteor pass, I will try it out and report.

**Comment by cytrinox** [comment]
The channel filter offset was the issue. New recording with zero offset works with converting to wav and demod with meteor_demod.
