### ISSUE TITLE
No PLL lock with recordings from Meteor M2 since v0.3

### ISSUE THREAD

**Issue by cytrinox** [dbdexter-dev/meteor_demod#9]
I have recordings from Meteor M2 which can be sucessfully demodulated by version v0.2.1 but not with v0.3. meteor_demod is unable to get PLL lock. For the moment, I use v0.2.1 for M2 and v0.3 only for M2-2 recordings.

A full recording from M2 is available at https://chaospixel.com/pub/rtlsdr/meteor_demod/broken/gqrx_20190908_085103_137100000_140000_fc.wav

I've tried it with meteor_demod *.wav and meteor_demod -m qpsk -r 72000 without luck.

**Comment by dbdexter-dev** [comment]
Hi, 
Commit a54192b should have fixed the issue with the PLL not locking. If you could build the 'devel' branch and check whether the problem is still there, that'd be fantastic.

**Comment by cytrinox** [comment]
Verified that it's fixed with the latest devel branch. Thank you!
